### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

POST http://localhost:8080/v1/producer/message
Content-Type: application/json

{
  "key": "738921783921h3kj21bnkjh3b21hb3jk21",
  "topic": "bSJPTxew",
  "message": "this is a new message"
}

###
POST http://localhost:8080/v1?
    topic={{$random.alphanumeric(8)}}
